language: swift
osx_image: xcode9.1

cache:
  - bundler
  - cocoapods

install:
  - bundle install
  - pod install

script:
  - set -o pipefail && \
    xcodebuild \
      -workspace Decoupler.xcworkspace \
      -scheme "Decoupler" \
      -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' \
      clean \
      build \
      test \
      # | tee "$CIRCLE_ARTIFACTS/xcodebuild-logs/xcodebuild-verbose.log"
      | xcpretty \
      # | tee "$CIRCLE_ARTIFACTS/xcodebuild-logs/xcodebuild-xcpretty.log"
