language: swift
osx_image: xcode9.1

cache:
  - bundler
  - cocoapods

install:
  - bundle install
  - pod install

script:
  - xcodebuild clean build test -workspace Decoupler.xcworkspace -scheme Decoupler -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest'
